default_context:
  project_name: 'fast-api-demo'
  project_slug: 'fast-api-demo'
  domain_main: 'fast-api-demo.com'
  domain_staging: 'stag.fast-api-demo.com'
  docker_swarm_stack_name_main: 'fast-api-demo-com'
  docker_swarm_stack_name_staging: 'stag-fast-api-demo-com'
  secret_key: '2844b05343c279ddc5dfc3ce5f7ccfcd0bb4c5eee13cfbffcb4398ef923863a0'
  first_superuser: 'root'
  first_superuser_password: '098poiA#'
  backend_cors_origins: '[A[B'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@fast-api-demo.com'
  postgres_password: 'changethis'
  pgadmin_default_user: 'root'
  pgadmin_default_user_password: '098poiA#'
  traefik_constraint_tag: 'fast-api-demo.com'
  traefik_constraint_tag_staging: 'stag.fast-api-demo.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:098poiA#'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
